networks:
  chatbot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  db:
    image: postgres:15
    container_name: chatbot_db
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: chatbot_api
    command: >
      sh -c "./wait-for-postgres.sh db &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 chatbot_api.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    networks:
      - chatbot_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_NAME=chatbot
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SECRET_KEY=your-secret-key-change-in-production
      - JWT_SECRET_KEY=your-jwt-secret-key-change-in-production
      - SECURE_SSL_REDIRECT=False
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: chatbot_nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:443"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
      - media_volume:/usr/share/nginx/html/media:ro
    networks:
      - chatbot_network
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume:
  nginx_logs: